### ISSUE TITLE
如何添加 systemd 文件

### ISSUE THREAD

**Issue by heykitin** [iuu6/gh-proxy#3]
创建 systemd 文件后显示 404 ，请问如何将 index.html 和 config.json 添加进去？

我是下载了 main.go 和 index.html 然后编辑了 config.json 都放在 /usr/local/ghapi 下，然后运行 go build main.go, 直接在该目录下执行 ./main 是没有问题的，然后创建了 ghapi.service 如下：

```systemd
[Unit]
Descriptio=Github Api
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/ghapi/main
Restart=always

[Install]
WantedBy=multi-user.target
```

运行后访问首页出现 404, 感觉是找不到 index.html 和 config.json 请问该如何解决-。 - 谢谢

**Comment by iuu6** [comment]
经过代码审查，我发现了以下问题
- `Descriptio`应该为`Description`

由于systemd默认使用**相对路径**，您可以尝试使用`WorkingDirectory`定义工作目录

```
[Unit]
Description=GitHub API
After=network.target

[Service]
Type=simple
WorkingDirectory=/usr/local/ghapi
ExecStart=/usr/local/ghapi/main
Restart=always

[Install]
WantedBy=multi-user.target
```

请尝试使用以下方式创建systemd并测试，感谢您的支持

**Comment by iuu6** [comment]
您的问题是否得以解决了？如果已解决请关闭此issue。
如果您在24小时内未回复，我将关闭此issue

感谢您的提议！

**Comment by heykitin** [comment]
> 经过代码审查，我发现了以下问题
> 
> * `Descriptio`应该为`Description`
> 
> 由于systemd默认使用**相对路径**，您可以尝试使用`WorkingDirectory`定义工作目录
> 
> ```
> [Unit]
> Description=GitHub API
> After=network.target
> 
> [Service]
> Type=simple
> WorkingDirectory=/usr/local/ghapi
> ExecStart=/usr/local/ghapi/main
> Restart=always
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> 请尝试使用以下方式创建systemd并测试，感谢您的支持

好的，谢谢，晚上回去试试，这两天在外地。

**Comment by heykitin** [comment]
> > 经过代码审查，我发现了以下问题
> > 
> > * `Descriptio`应该为`Description`
> > 
> > 由于systemd默认使用**相对路径**，您可以尝试使用`WorkingDirectory`定义工作目录
> > ```
> > [Unit]
> > Description=GitHub API
> > After=network.target
> > 
> > [Service]
> > Type=simple
> > WorkingDirectory=/usr/local/ghapi
> > ExecStart=/usr/local/ghapi/main
> > Restart=always
> > 
> > [Install]
> > WantedBy=multi-user.target
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 请尝试使用以下方式创建systemd并测试，感谢您的支持
> 
> 好的，谢谢，晚上回去试试，这两天在外地。

成功了，十分感谢
